name: Add post

on:
  push:
    branches:
      - main
    paths:
      - "add-new-posts-here/**"

jobs:
  run-script-job:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code
        with:
          fetch-depth: 0

      - name: Download Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Create, Install, Run
        run: |
          python -m venv ./scripts/venv
          source ./scripts/venv/bin/activate

      - name: Install dependencies
        run: |
          source ./scripts/venv/bin/activate
          pip install -r ./scripts/requirements.txt

      - name: Run script on last committed file (push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          set -Eeuo pipefail
          source ./scripts/venv/bin/activate
          # List files in the current commit (no metadata), pick the last line
          input_file="$(git show --name-only --pretty='' "${GITHUB_SHA}" | tail -n 1)"
          echo "Resolved input file: '$input_file'"
          if [[ -z "$input_file" ]]; then
            echo "No file found in commit ${GITHUB_SHA}"; exit 1
          fi
          python ./scripts/create-post-from-url.py --input-file "$input_file" --output-path ./_posts/

      - name: Add new blog post
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./_posts/$input_file
          git commit -m "[GitHub Actions] Add new blog post from $input_file"
          git push
